stages:
  - build
  - ci_status
  - deploy

variables: &default_variables
  GIT_SUBMODULE_STRATEGY: recursive
  BASIC_PACKAGES: "environment-modules make git which cmake findutils"
  SCENE_PACKAGES: "netcdf-fortran netcdf-devel netcdf-fortran-devel gcc gcc-gfortran"
  PYTHON_PACKAGES: "python python3 python3-pip python3-devel"
  EXTRA_PACKAGES: ""
  WITH_PYTHON: "no"
  GHOST_DIR: "~/ghost"
  GHOST_BUILD_DIR: "~/ghost/build"
  GHOST_INSTALL_DIR: "~/ghost/build/install"

.install_main_packages: &install_main_packages
  - dnf install -y ${BASIC_PACKAGES} ${SCENE_PACKAGES} ${PYTHON_PACKAGES} ${EXTRA_PACKAGES}
  - if [ "x"${WITH_PYTHON} == "xyes" ]; then pip3 install -U pip; fi
  - if [ "x"${WITH_PYTHON} == "xyes" ]; then pip3 install -r requirements.txt; fi

.install_ghost: &install_ghost
  - git clone https://github.com/ZedThree/GHOST.git ${GHOST_DIR}
  - mkdir -p ${GHOST_BUILD_DIR} && cd ${GHOST_BUILD_DIR}
  - ../configure --prefix ${GHOST_INSTALL_DIR}
  - make -j && make install

.default_script: &default_script
  - sh .ci_scripts/ci_build.sh

default:
  timeout: 20m
  artifacts:
    paths:
  before_script:
    - *install_main_packages
    - *install_ghost
  after_script:
  interruptible: true


standard:
  stage: build
  image: fedora:31
  variables:
    CASENAME: "standard"
  script: *default_script
